# Generated by Django 3.1.7 on 2021-02-21 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210221_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='option',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.options', verbose_name='Выбранные вариант ответа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='test',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.test'),
        ),
    ]
